import os

# Basic config
BROKER_URL = os.getenv('CLOUDAMQP_URL', 'amqp://localhost')
CELERY_DEFAULT_RATE_LIMIT = '100/s'
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERY_MESSAGE_COMPRESSION = 'gzip'
# CELERY_DISABLE_RATE_LIMITS = True
# Tasks
CELERY_TASK_SERIALIZER = 'pickle'
CELERYD_TASK_TIME_LIMIT = 10 * 60
# Results
CELERY_TASK_RESULT_EXPIRES = 7200  # 2 hours.
CELERY_RESULT_BACKEND = os.getenv('REDISTOGO_URL', 'redis://')
CELERY_RESULT_SERIALIZER = 'json'
